### ISSUE TITLE
minor change to .ycm_extra_conf.py

### ISSUE THREAD

**Issue by Litchiware** [JDevlieghere/dotfiles#2]
Very good idea to define a function in [ycm_extra_conf.py](https://github.com/JDevlieghere/dotfiles/blob/master/.vim/.ycm_extra_conf.py#L105) to add project's include directory and its subdirectories to compilation flags. But I think the `flag` variable should be initialized to `["-I" + include_path]` instead of `[]`, because we want to track headers not only in subdirectories but also in `include_path`.

```
def FlagsForInclude(root):
    try:
        include_path = FindNearest(root, 'include')
        flags = ["-I" + include_path] # flags = []
        for dirroot, dirnames, filenames in os.walk(include_path):
            for dir_path in dirnames:
                real_path = os.path.join(dirroot, dir_path)
                flags = flags + ["-I" + real_path]
        return flags
    except:
        return None
```

**Comment by JDevlieghere** [comment]
I think you are right, thanks for spotting that! You can make a pull-request or I can update file for you if you want.

Cheers,
Jonas

**Comment by JDevlieghere** [comment]
Because `os.walk` returns its root too this isn't necessary and we'd just end up with two instances of the same path.
